"use client"

import React from "react"
import {
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiGooglecloud,
  SiGithubactions,
  SiJenkins,
  SiRedhatopenshift,
  SiAnsible,
  SiSonar,
  SiNodedotjs,
  SiExpress,
  SiSpringboot,
  SiPython,
  SiFastapi,
  SiNestjs,
  SiGraphql,
  SiC,
  SiAnthropic,
  SiOpenai,
  SiN8N,
  SiOllama,
  SiHuggingface,
  SiTypescript,
  SiJavascript,
  SiReact,
  SiNextdotjs,
  SiTailwindcss,
  SiRedux,
  SiAngular,
  SiHtml5,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiMysql,
  SiSqlite,
  SiDrizzle,
  SiDynatrace,
  SiPosthog,
  SiProxmox,
  SiTailscale,
  SiNginx,
  SiPostman,
  SiKibana,
  SiFigma,
  SiLinux,
  SiLatex,
  SiStripe,
  SiSolidity,
  SiSanity,
  SiFlask,
  SiGrafana,
  SiPrometheus,
} from "react-icons/si"
import { FaAws } from "react-icons/fa6"
import { VscAzure, VscAzureDevops } from "react-icons/vsc"
import { GrOracle } from "react-icons/gr"
import {
  Boxes,
  Database,
  GitBranch,
  Kanban,
  Layers,
  Network,
  ShieldCheck,
  Smartphone,
  Terminal,
  Activity,
  Cpu,
  Mail,
  Workflow,
  Sparkles,
} from "lucide-react"

const techIconMap: Record<string, React.ComponentType<{ className?: string }>> = {
  // DevOps & Cloud Infrastructure
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  aks: SiKubernetes,
  terraform: SiTerraform,
  aws: FaAws,
  gcp: SiGooglecloud,
  azure: VscAzure,
  "azure devops": VscAzureDevops,
  "azure ai foundry": VscAzure,
  "ci/cd": GitBranch,
  "github actions": SiGithubactions,
  jenkins: SiJenkins,
  openshift: SiRedhatopenshift,
  ansible: SiAnsible,
  sonarqube: SiSonar,
  "unix/linux": SiLinux,
  linux: SiLinux,
  proxmox: SiProxmox,
  "proxmox ve": SiProxmox,

  // Backend & Systems Engineering
  "node.js": SiNodedotjs,
  node: SiNodedotjs,
  "express.js": SiExpress,
  express: SiExpress,
  "java spring boot": SiSpringboot,
  "spring boot": SiSpringboot,
  python: SiPython,
  flask: SiFlask,
  fastapi: SiFastapi,
  nestjs: SiNestjs,
  "restful apis": Network,
  "rest apis": Network,
  microservices: Boxes,
  graphql: SiGraphql,
  "posix / c": SiC,
  "c (posix)": SiC,
  c: SiC,
  sockets: Network,

  // AI & Platform Engineering
  "mcp (model context protocol)": SiAnthropic,
  "mcp servers": SiAnthropic,
  "ai / mcp": SiAnthropic,
  mcp: SiAnthropic,
  "multi-agent systems": Sparkles,
  "multi-agents": Sparkles,
  "llm integration": Sparkles,
  "llm apis": SiOpenai,
  rag: Database,
  "n8n automation": SiN8N,
  n8n: SiN8N,
  ollama: SiOllama,
  huggingface: SiHuggingface,
  "prompt engineering": Terminal,
  automation: Cpu,

  // Frontend Development
  typescript: SiTypescript,
  javascript: SiJavascript,
  "react.js": SiReact,
  react: SiReact,
  "next.js": SiNextdotjs,
  "next.js 15": SiNextdotjs,
  "tailwind css": SiTailwindcss,
  tailwind: SiTailwindcss,
  redux: SiRedux,
  angular: SiAngular,
  "html5 / css3": SiHtml5,
  html5: SiHtml5,
  "responsive ui": Smartphone,
  pwa: Smartphone,
  "web design": Layers,
  "ui/ux": SiFigma,
  figma: SiFigma,

  // Databases & Storage
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mongodb: SiMongodb,
  redis: SiRedis,
  mysql: SiMysql,
  sqlite: SiSqlite,
  "oracle sql": GrOracle,
  oracle: GrOracle,
  "neon postgres": SiPostgresql,
  neon: SiPostgresql,
  "drizzle orm": SiDrizzle,
  drizzle: SiDrizzle,
  cms: Database,
  "sanity cms": SiSanity,

  // Observability, Security & Tooling
  "dynatrace ai": SiDynatrace,
  dynatrace: SiDynatrace,
  grafana: SiGrafana,
  prometheus: SiPrometheus,
  posthog: SiPosthog,
  netbird: ShieldCheck,
  tailscale: SiTailscale,
  nginx: SiNginx,
  servicenow: Workflow,
  postman: SiPostman,
  kibana: SiKibana,
  "microsoft planner": Kanban,
  "scrum master": Kanban,
  scrum: Kanban,
  "agile / scrum": Kanban,
  devsecops: ShieldCheck,
  sre: Activity,
  zabbix: Activity,
  stripe: SiStripe,
  solidity: SiSolidity,
  zkps: ShieldCheck,
  latex: SiLatex,
  resend: Mail,
  "api integrations": Network,
}

export function TechIcon({
  name,
  className = "h-3.5 w-3.5",
}: {
  name: string
  className?: string
}) {
  const normalized = name.trim().toLowerCase()
  const IconComponent = techIconMap[normalized] || Terminal
  return <IconComponent className={className} />
}
